---
nodeGroups:
  master:
    nodes:
    - "192.168.1.111"
    - "192.168.1.112"
  master_arm64:
    spec:
      labels:
        - "node-role.kubernetes.io/master"
      taints:
        - "node-role.kubernetes.io/master=:NoSchedule"
        - "beta.kubernetes.io/arch=arm64=:NoSchedule"
      kubernetes:
        image:
          repository: "gcr.io/google_containers/hyperkube-arm64"
    nodes:
    - "192.168.1.113"
  worker:
    nodes:
    - "192.168.1.121"
  worker_arm64:
    spec:
      taints:
        - "beta.kubernetes.io/arch=arm64=:NoSchedule"
      kubernetes:
        image:
          repository: "gcr.io/google_containers/hyperkube-arm64"
      labels:
        - "node-role.kubernetes.io/master-arm64"
        - "node-role.kubernetes.io/master"
    nodes:
    - "192.168.1.131"
  worker_arm:
    spec:
      taints:
        - "beta.kubernetes.io/arch=arm=:NoSchedule"
      kubernetes:
        image:
          repository: "gcr.io/google_containers/hyperkube-arm"
    nodes:
    - "192.168.1.141"

spec:
  kubernetes:
    image:
      repository: "gcr.io/google_containers/hyperkube"
      tag: "v1.8.2"
      pullPolicy: "Always"
  labels:
    - "node-role.kubernetes.io/master-default"
    - "node-role.kubernetes.io/master"
