---
user: ubuntu

local:
  assets_dir: "~/.kube/openstack"

masters: &masters
  - 172.16.2.121
  - 172.16.2.122
  - 172.16.2.123
workers: &workers
  - 172.16.2.131
  - 172.16.2.132
  - 172.16.2.133

roledefs:
  bootstrap:
  - 172.16.2.121
  etcd: *masters
  master: *masters
  worker: *workers

kubernetes:
  public_service_ip: 172.16.2.101
  network_plugin: "kubenet"
  cloud_provider: "openstack"
  # cloud_config file path must be under /etc/kubernetes directory to share
  # with each kubelet, apiserver and controller_manager.
  cloud_config: /etc/kubernetes/openstack.conf

etcd:
  hosts:
    "172.16.2.121": cow001.local
    "172.16.2.122": cow002.local
    "172.16.2.123": cow003.local

openstack:
  auth_url: http://192.168.11.197/identity/v3/
  username: demo
  password: openstack
  region_name: RegionOne
  tenant_name: demo
  user_domain_id: default
  subnet_name: k8s-subnet
  floating_network_name: public
  router_name: k8s-router
